Testing whether it is possible to say that the ith largest eigenvalue of XAX^T is close to the ith largest eigenvalue of XBX^T, when the ith largest eigenvalue of A and the ith largest eigenvalue of B are close, where X is a nxd matrix whose rows are orthonormal. The answer is no. It seems that a certain number of eigenvalues are unchanged and the other are anywhere between the lambda_max(A) - lambda_min(B).

In [32]:
import numpy as np
from preconditioners.utils import *
from scipy.stats import ortho_group

In [33]:
n = 12
d = 20
sigma2 = 0.05
r2 = 1

In [34]:
c = generate_c(ro=0.5, regime='autoregressive', d=d)
c_inv = np.linalg.inv(c)

In [35]:
w_star = generate_true_parameter(d, r2=r2, m=np.eye(d))
X, y, _ = generate_centered_linear_gaussian_data(w_star, c, n, d, sigma2)

/Users/eduardoravkin/Desktop/ml_research/phd/preconditioners/src/preconditioners/utils.py:329: UserWarning: Warning, norms of datapoints are not sqrt(d)
  warnings.warn('Warning, norms of datapoints are not sqrt(d)')


In [36]:
m = ortho_group.rvs(dim=d)
m = m[:n,:]

v = ortho_group.rvs(dim=d)
D = np.diag(np.concatenate((np.ones(int(d/2)),10*np.ones(int(d/2)))))

In [37]:
m_1.shape

(12, 20)

In [62]:
from scipy.stats import ortho_group
n = 2
d = 20

m_1 = ortho_group.rvs(dim=d)
m_1= m_1[:n,:]

d1 = np.diag(np.arange(d))
d2 = np.diag(np.random.uniform(0,1,d)+1)


In [63]:
np.linalg.norm(m_1.dot(m_1.T) - np.eye(n))

8.317708426610503e-16

In [64]:
a = m_1.dot(d1).dot(m_1.T)
b = m_1.dot(d2).dot(m_1.T)

In [65]:
np.linalg.eigh(a)[0]

array([ 4.47564658, 10.6706513 ])

In [66]:
np.linalg.eigh(b)[0]

array([1.43438595, 1.65404587])

In [67]:
np.linalg.eigh(a+b)[0]

array([ 5.91517188, 12.31955783])

In [43]:
b.dot(a) - a.dot(b)

array([[ 0.00000000e+00,  2.13603308e-01,  1.62731828e-01,
         2.14600598e-01,  6.05159532e-02,  1.31525067e-01,
         2.97249004e-01,  4.76670100e-01,  4.66157290e-01,
         3.37116840e-01,  2.97637528e-01, -1.65957787e-02],
       [-2.13603308e-01,  1.77635684e-15, -1.81115489e-02,
        -1.14559449e-01, -1.84583336e-02, -5.55855675e-01,
        -1.07527020e-01,  4.23107875e-01, -8.11095164e-01,
        -6.47273296e-01, -2.21563809e-02, -2.28672465e-01],
       [-1.62731828e-01,  1.81115489e-02,  0.00000000e+00,
        -1.69940172e-01,  4.25712467e-02, -4.68813669e-02,
         1.04732993e-01,  1.03272612e-01, -2.09188965e-01,
        -2.24492534e-01, -1.67650849e-02,  4.52479114e-02],
       [-2.14600598e-01,  1.14559449e-01,  1.69940172e-01,
         0.00000000e+00,  2.27147258e-01,  2.28090702e-01,
         4.71809535e-01, -5.68162643e-02, -1.22563322e-01,
         4.25033525e-01,  2.24739513e-01, -2.86875339e-01],
       [-6.05159532e-02,  1.84583336e-02, -4.2571246

In [62]:
#A = np.diag(np.arange(d)+1)
A = np.eye(d)
B = A + D

In [63]:
np.linalg.eig(m.dot(A.dot(m.T)))[0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
np.linalg.eig(m.dot(B.dot(m.T)))[0]

array([ 4.57344151,  5.60455737,  7.55892336,  8.28110331, 10.63472612,
       10.11501633,  2.71866207,  2.11116061, 11.        , 11.        ,
        2.        ,  2.        ])